"""ajout colonnes chapter et nouvelles tables

Revision ID: e210f7a716fc
Revises: 3907a7d0df55
Create Date: 2026-04-21 15:15:38.407005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e210f7a716fc'
down_revision: Union[str, None] = '3907a7d0df55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('music_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'music_title')
    # ### end Alembic commands ###
